name: buildx

on:
  push:
    branches: [master]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: executing remote ssh commands and pulling from git and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /home/professional_institute/professional_Institute_backend/
            sudo git pull origin master
            mtushar78@gmail.com
            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
            sudo pm2 start index